version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'

    volumes:
      - 'certs:/etc/nginx/certs:ro'
      - 'cache:/var/cache/nginx'
      - 'vhost:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
      - 'conf:/etc/nginx/conf.d'
    networks:
      - default

  nginx-gen:
    image: jwilder/docker-gen:latest
    container_name: nginx-gen
    restart: always
    volumes_from:
      - nginx
    volumes:
      - 'templates:/etc/docker-gen/templates'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    command:  -notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    
volumes:
  cache: {}
  certs: {}
  vhost: {}
  html: {}
  conf: {}
  templates: {}