nginx-proxy:
  image: jwilder/nginx-proxy
  container_name: nginx_proxy
  restart: always
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - 'nginx_proxy_certs:/etc/nginx/certs'
    - 'nginx_proxy_cache:/var/cache/nginx'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'